**Task-1**

Importing required Libraries


In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import cv2

from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D 
from keras.utils import np_utils
import sklearn.metrics as metrics 

In [2]:
import os, sys
from IPython.display import display
from IPython.display import Image as _Imgdis
from PIL import Image
from numpy import asarray
from scipy import ndimage
from keras.preprocessing.image import ImageDataGenerator, array_to_img, img_to_array, load_img

In [6]:
train = "/content/drive/MyDrive/MIDAS/Task2/train"              # importing train dataset
folder_names = os.listdir(train)                                # listing sub folders in train
folder_names

['Sample054',
 'Sample056',
 'Sample062',
 'Sample060',
 'Sample055',
 'Sample057',
 'Sample061',
 'Sample059',
 'Sample058',
 'Sample053',
 'Sample052',
 'Sample047',
 'Sample051',
 'Sample043',
 'Sample046',
 'Sample050',
 'Sample045',
 'Sample049',
 'Sample048',
 'Sample044',
 'Sample033',
 'Sample038',
 'Sample036',
 'Sample040',
 'Sample039',
 'Sample035',
 'Sample042',
 'Sample034',
 'Sample041',
 'Sample037',
 'Sample026',
 'Sample028',
 'Sample032',
 'Sample027',
 'Sample030',
 'Sample023',
 'Sample025',
 'Sample024',
 'Sample029',
 'Sample031',
 'Sample019',
 'Sample016',
 'Sample014',
 'Sample015',
 'Sample020',
 'Sample021',
 'Sample017',
 'Sample022',
 'Sample018',
 'Sample013',
 'Sample007',
 'Sample006',
 'Sample010',
 'Sample005',
 'Sample004',
 'Sample012',
 'Sample008',
 'Sample009',
 'Sample003',
 'Sample011',
 'Sample001',
 'Sample002']

In [8]:
img_ext = '*.png'                                             # Extractive image file names in every sub-folder
import glob

for indx, folder_name in enumerate(folder_names):
    file_dir =  os.path.join(train,folder_name,img_ext)
   
    img_list = glob.glob(file_dir)
img_list

['/content/drive/MyDrive/MIDAS/Task2/train/Sample002/img002-002.png',
 '/content/drive/MyDrive/MIDAS/Task2/train/Sample002/img002-018.png',
 '/content/drive/MyDrive/MIDAS/Task2/train/Sample002/img002-046.png',
 '/content/drive/MyDrive/MIDAS/Task2/train/Sample002/img002-049.png',
 '/content/drive/MyDrive/MIDAS/Task2/train/Sample002/img002-013.png',
 '/content/drive/MyDrive/MIDAS/Task2/train/Sample002/img002-052.png',
 '/content/drive/MyDrive/MIDAS/Task2/train/Sample002/img002-019.png',
 '/content/drive/MyDrive/MIDAS/Task2/train/Sample002/img002-038.png',
 '/content/drive/MyDrive/MIDAS/Task2/train/Sample002/img002-021.png',
 '/content/drive/MyDrive/MIDAS/Task2/train/Sample002/img002-011.png',
 '/content/drive/MyDrive/MIDAS/Task2/train/Sample002/img002-025.png',
 '/content/drive/MyDrive/MIDAS/Task2/train/Sample002/img002-047.png',
 '/content/drive/MyDrive/MIDAS/Task2/train/Sample002/img002-048.png',
 '/content/drive/MyDrive/MIDAS/Task2/train/Sample002/img002-040.png',
 '/content/drive/MyD

Code for making the custom dataset from the given folder (train)


Converting .png image files to arrays and adding labels to the corresponding image.

In [10]:
import glob                                                     

path = train
folder_names = os.listdir(path)
img_ext = '*.png'

X = []
y = []
w = 28
h = 28

for indx, folder_name in enumerate(sorted(folder_names)):
    file_dir =  os.path.join(path,folder_name,img_ext)
   
    img_list = glob.glob(file_dir)
   
    for img in img_list:
        # Read and resize image
        imread_e = cv2.imread(img)
        X.append(cv2.resize(imread_e, (w,h), interpolation=cv2.INTER_CUBIC))
        y.append([0]*(indx) + [1] + [0]*(len(folder_names)-(1+indx)))

X = np.array(X)
y = np.array(y)

y is an array such that the class is one hot encoded at the respective position. For eg. since there are 40 images of each class in the dataset among 62 classes, y[0] : y[39] belong to the first class and so on.

In [24]:
y[0]

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
y[39]

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
y[40]

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
from sklearn.model_selection import train_test_split

Splitting Dataset into train and test. (Best test size = 0.2)

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=42)

Printing shape of X_train and y_train

In [16]:
print(X_train.shape)
print(y_train.shape)

(1984, 28, 28, 3)
(1984, 62)


In [18]:
y_train[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
y_train[1]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [27]:
from keras.losses import categorical_crossentropy
from keras.models import Sequential
from keras import layers
from keras.utils import np_utils
import sklearn.metrics as metrics

A CNN Model from scratch.
After lot of iterations and training, the values of variables have been selected. INcreasing the depth of the network more than this only lead to overfitting and reduction in validation accuracy significantly.

In [57]:
model1 = Sequential()
model1.add(Conv2D(filters=64, kernel_size=(5,5), padding = 'same', activation='relu', input_shape=(28, 28, 3)))
model1.add(MaxPooling2D(pool_size=(2,2), strides = (2,2)))
model1.add(Conv2D(filters=32, kernel_size=(3,3), padding = 'same', activation='relu'))
model1.add(MaxPooling2D(pool_size=(2,2)))
model1.add(Flatten())
model1.add(Dense(units=128, activation='relu'))
model1.add(Dropout(0.2))
model1.add(Dense(units = 62, activation='softmax'))

model1.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_13 (Conv2D)           (None, 28, 28, 64)        4864      
_________________________________________________________________
max_pooling2d_13 (MaxPooling (None, 14, 14, 64)        0         
_________________________________________________________________
conv2d_14 (Conv2D)           (None, 14, 14, 32)        18464     
_________________________________________________________________
max_pooling2d_14 (MaxPooling (None, 7, 7, 32)          0         
_________________________________________________________________
flatten_4 (Flatten)          (None, 1568)              0         
_________________________________________________________________
dense_11 (Dense)             (None, 128)               200832    
_________________________________________________________________
dropout_6 (Dropout)          (None, 128)              

Compiling model with Adam as optimizer

In [58]:
# train
model1.compile(optimizer='Adam', loss = 'categorical_crossentropy', metrics=['accuracy'])

Saving model checkpoints

In [66]:
from keras.callbacks import ModelCheckpoint, EarlyStopping
es = EarlyStopping(monitor='val_acc', verbose=1, patience=5)
mc = ModelCheckpoint(filepath='task1.h5', verbose=1, monitor='val_acc')
cb = [es, mc]

After around 20 epochs, the model saturates training process with best batch size of 64 given the small dataset of around 2480 images.
The max valdation accuracy comes around 60 % which is not bad for such small dataset.
 

In [67]:
history1 = model1.fit(X_train,y_train, batch_size= 64, epochs=25,validation_data=(X_test, y_test), verbose=1, callbacks=cb)

Epoch 1/25
31/31 [==============================] - 0s 7ms/step - loss: 0.0884 - accuracy: 0.9824 - val_loss: 12.3238 - val_accuracy: 0.5685

Epoch 00001: saving model to task1.h5
Epoch 2/25
31/31 [==============================] - 0s 6ms/step - loss: 0.0882 - accuracy: 0.9859 - val_loss: 11.8597 - val_accuracy: 0.5907

Epoch 00002: saving model to task1.h5
Epoch 3/25
31/31 [==============================] - 0s 6ms/step - loss: 0.0713 - accuracy: 0.9844 - val_loss: 13.6603 - val_accuracy: 0.5625

Epoch 00003: saving model to task1.h5
Epoch 4/25
31/31 [==============================] - 0s 6ms/step - loss: 0.1345 - accuracy: 0.9788 - val_loss: 10.9062 - val_accuracy: 0.5423

Epoch 00004: saving model to task1.h5
Epoch 5/25
31/31 [==============================] - 0s 6ms/step - loss: 0.1858 - accuracy: 0.9733 - val_loss: 11.2557 - val_accuracy: 0.5605

Epoch 00005: saving model to task1.h5
Epoch 6/25
31/31 [==============================] - 0s 6ms/step - loss: 0.1113 - accuracy: 0.9824 - 

**Task-2**

In [68]:
train2 = "/content/drive/MyDrive/MIDAS/Task2/train_0-9"

In [70]:
folder_names2 = os.listdir(train2)
folder_names2

['Sample007',
 'Sample006',
 'Sample003',
 'Sample004',
 'Sample005',
 'Sample002',
 'Sample010',
 'Sample009',
 'Sample001',
 'Sample008']

In [71]:
path2 = train2
folder_names2 = os.listdir(path2)
img_ext = '*.png'

X2 = []
y2 = []
w2 = 100
h2 = 100

for indx, folder_name in enumerate(sorted(folder_names2)):
    file_dir =  os.path.join(path,folder_name,img_ext)
   
    img_list2 = glob.glob(file_dir)
   
    for img in img_list2:
        # Read and resize image
        imread_e = cv2.imread(img)
        X2.append(cv2.resize(imread_e, (w,h), interpolation=cv2.INTER_CUBIC))
        y2.append([0]*(indx) + [1] + [0]*(len(folder_names2)-(1+indx)))

X2 = np.array(X2)
y2 = np.array(y2)

In [74]:
from keras.applications import VGG19

In [75]:
from keras import layers
from keras import models

In [76]:
from keras.datasets import mnist
(X_train2, y_train2), (X_test2, y_test2) = mnist.load_data()

Resizing the traning and testing data (MNIST) for input to the VGG19 (accepts minimum size of 32)

In [77]:
import cv2
IMG_SIZE = 32
def resize(img_array):
    tmp = np.empty((img_array.shape[0], IMG_SIZE, IMG_SIZE))

    for i in range(len(img_array)):
        img = img_array[i].reshape(28, 28).astype('uint8')
        img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
        img = img.astype('float32')/255
        tmp[i] = img
        
    return tmp

X_train2 = resize(X_train2)
X_test2 = resize(X_test2)

In [78]:
X_train2 = np.stack((X_train2,)*3, axis=-1)
X_test2 = np.stack((X_test2,)*3, axis=-1)
print(X_train2.shape)
print(X_test2.shape)

(60000, 32, 32, 3)
(10000, 32, 32, 3)


In [79]:
from keras.utils import to_categorical
y_train2 = to_categorical(y_train2, num_classes=10)
print(y_train2.shape)
y_test2 = to_categorical(y_test2, num_classes=10)
print(y_test2.shape)

(60000, 10)
(10000, 10)


In [80]:
vgg19 = VGG19(weights = 'imagenet', include_top=False, input_shape = (32, 32, 3))

In [82]:
model2 = Sequential()
model2.add(vgg19)
model2.add(Flatten())
model2.add(Dense(10, activation='softmax'))
model2.compile(loss='categorical_crossentropy', 
              optimizer='Adam', 
              metrics=['accuracy'])

model2.summary()

Model: "sequential_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
vgg19 (Functional)           (None, 1, 1, 512)         20024384  
_________________________________________________________________
flatten_6 (Flatten)          (None, 512)               0         
_________________________________________________________________
dense_14 (Dense)             (None, 10)                5130      
Total params: 20,029,514
Trainable params: 20,029,514
Non-trainable params: 0
_________________________________________________________________


In [83]:
from keras.callbacks import ModelCheckpoint, EarlyStopping
es = EarlyStopping(monitor='val_acc', verbose=1, patience=5)
mc = ModelCheckpoint(filepath='mnist-vgg19.h5', verbose=1, monitor='val_acc')
cb = [es, mc]

In [85]:
history2 = model2.fit(X_train2, y_train2, 
                    epochs=50, 
                    batch_size=128, 
                    validation_data=(X_test2, y_test2),
                    callbacks=cb)

Epoch 1/50
469/469 [==============================] - 31s 66ms/step - loss: 0.0600 - accuracy: 0.9855 - val_loss: 0.0378 - val_accuracy: 0.9911

Epoch 00001: saving model to mnist-vgg19.h5
Epoch 2/50
469/469 [==============================] - 31s 67ms/step - loss: 0.0438 - accuracy: 0.9903 - val_loss: 0.0560 - val_accuracy: 0.9901

Epoch 00002: saving model to mnist-vgg19.h5
Epoch 3/50
469/469 [==============================] - 31s 67ms/step - loss: 0.0552 - accuracy: 0.9879 - val_loss: 0.0567 - val_accuracy: 0.9864

Epoch 00003: saving model to mnist-vgg19.h5
Epoch 4/50
469/469 [==============================] - 31s 67ms/step - loss: 0.0355 - accuracy: 0.9917 - val_loss: 0.0355 - val_accuracy: 0.9914

Epoch 00004: saving model to mnist-vgg19.h5
Epoch 5/50
469/469 [==============================] - 32s 68ms/step - loss: 0.0430 - accuracy: 0.9905 - val_loss: 0.0487 - val_accuracy: 0.9877

Epoch 00005: saving model to mnist-vgg19.h5
Epoch 6/50
469/469 [==============================] - 3

At te end of 50 epochs:
Training accuracy : 0.9988
Validation accuracy : 0.9947

This tells us that the accuarcy is pretty good for the pretrained model.

Using the same model1 from Task-1 to compare the performance on MNIST dataset in comparison to pretrained network


(model1 = model3)

In [91]:
model3 = Sequential()
model3.add(Conv2D(filters=64, kernel_size=(5,5), padding = 'same', activation='relu', input_shape=(32, 32, 3)))
model3.add(MaxPooling2D(pool_size=(2,2), strides = (2,2)))
model3.add(Conv2D(filters=32, kernel_size=(3,3), padding = 'same', activation='relu'))
model3.add(MaxPooling2D(pool_size=(2,2)))
model3.add(Flatten())
model3.add(Dense(units=128, activation='relu'))
model3.add(Dropout(0.2))
model3.add(Dense(units = 10, activation='softmax'))

model3.summary()

Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_17 (Conv2D)           (None, 32, 32, 64)        4864      
_________________________________________________________________
max_pooling2d_17 (MaxPooling (None, 16, 16, 64)        0         
_________________________________________________________________
conv2d_18 (Conv2D)           (None, 16, 16, 32)        18464     
_________________________________________________________________
max_pooling2d_18 (MaxPooling (None, 8, 8, 32)          0         
_________________________________________________________________
flatten_8 (Flatten)          (None, 2048)              0         
_________________________________________________________________
dense_17 (Dense)             (None, 128)               262272    
_________________________________________________________________
dropout_8 (Dropout)          (None, 128)             

In [92]:
model3.compile(optimizer='Adam', loss = 'categorical_crossentropy', metrics=['accuracy'])

In [93]:
from keras.callbacks import ModelCheckpoint, EarlyStopping
es = EarlyStopping(monitor='val_acc', verbose=1, patience=5)
mc = ModelCheckpoint(filepath='random_model.h5', verbose=1, monitor='val_acc')
cb = [es, mc]

In [94]:
history2 = model3.fit(X_train2, y_train2, 
                    epochs=50, 
                    batch_size=128, 
                    validation_data=(X_test2, y_test2),
                    callbacks=cb)

Epoch 1/50
469/469 [==============================] - 4s 7ms/step - loss: 0.4510 - accuracy: 0.8598 - val_loss: 0.0468 - val_accuracy: 0.9861

Epoch 00001: saving model to random_model.h5
Epoch 2/50
469/469 [==============================] - 3s 7ms/step - loss: 0.0617 - accuracy: 0.9805 - val_loss: 0.0320 - val_accuracy: 0.9896

Epoch 00002: saving model to random_model.h5
Epoch 3/50
469/469 [==============================] - 3s 7ms/step - loss: 0.0393 - accuracy: 0.9876 - val_loss: 0.0320 - val_accuracy: 0.9896

Epoch 00003: saving model to random_model.h5
Epoch 4/50
469/469 [==============================] - 3s 7ms/step - loss: 0.0302 - accuracy: 0.9903 - val_loss: 0.0279 - val_accuracy: 0.9910

Epoch 00004: saving model to random_model.h5
Epoch 5/50
469/469 [==============================] - 3s 7ms/step - loss: 0.0252 - accuracy: 0.9918 - val_loss: 0.0276 - val_accuracy: 0.9914

Epoch 00005: saving model to random_model.h5
Epoch 6/50
469/469 [==============================] - 3s 7ms

At te end of 50 epochs:
Training accuracy : 0.9990
Validation accuracy : 0.9931

Our model of random initial weights also does pretty good on the same training data. 
Pre-trained model (model-2)just slightly surpasses the model 3 in terms of validation accuracy.


In terms of convergence time, the random weight model (model-3) converges much faster (almost near first 10 epochs) than pre-trainined model (model-2)


**Task-3**

The dataset given is not well understood. Since the parent folder has subfolders labelled as 0 to 9 for the respective classes, but the images inside the subfolders have random images of any digit from 0-9 (6000 approx in every subfolder), it is impossible to train the dataset with wrong labels. 